spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: sw
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml

sensitive-words:
  cache:
    words:
      scheduled-refresh-enabled: false
  security:
    basic:
      password: test-password
