USE SensitiveWordsDb;
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

SET NOCOUNT ON;
GO

DECLARE @sql_keywords TABLE (
    word NVARCHAR(510) NOT NULL
);

INSERT INTO @sql_keywords (word)
VALUES
    (N'ACTION'),
    (N'ADD'),
    (N'ALL'),
    (N'ALLOCATE'),
    (N'ALTER'),
    (N'ANY'),
    (N'APPLICATION'),
    (N'ARE'),
    (N'AREA'),
    (N'ASC'),
    (N'ASSERTION'),
    (N'ATOMIC'),
    (N'AUTHORIZATION'),
    (N'AVG'),
    (N'BEGIN'),
    (N'BY'),
    (N'CALL'),
    (N'CASCADE'),
    (N'CASCADED'),
    (N'CATALOG'),
    (N'CHECK'),
    (N'CLOSE'),
    (N'COLUMN'),
    (N'COMMIT'),
    (N'COMPRESS'),
    (N'CONNECT'),
    (N'CONNECTION'),
    (N'CONSTRAINT'),
    (N'CONSTRAINTS'),
    (N'CONTINUE'),
    (N'CONVERT'),
    (N'CORRESPONDING'),
    (N'CREATE'),
    (N'CROSS'),
    (N'CURRENT'),
    (N'CURRENT_PATH'),
    (N'CURRENT_SCHEMA'),
    (N'CURRENT_SCHEMAID'),
    (N'CURRENT_USER'),
    (N'CURRENT_USERID'),
    (N'CURSOR'),
    (N'DATA'),
    (N'DEALLOCATE'),
    (N'DECLARE'),
    (N'DEFAULT'),
    (N'DEFERRABLE'),
    (N'DEFERRED'),
    (N'DELETE'),
    (N'DESC'),
    (N'DESCRIBE'),
    (N'DESCRIPTOR'),
    (N'DETERMINISTIC'),
    (N'DIAGNOSTICS'),
    (N'DIRECTORY'),
    (N'DISCONNECT'),
    (N'DISTINCT'),
    (N'DO'),
    (N'DOMAIN'),
    (N'DOUBLEATTRIBUTE'),
    (N'DROP'),
    (N'EACH'),
    (N'EXCEPT'),
    (N'EXCEPTION'),
    (N'EXEC'),
    (N'EXECUTE'),
    (N'EXTERNAL'),
    (N'FETCH'),
    (N'FLOAT'),
    (N'FOREIGN'),
    (N'FOUND'),
    (N'FULL'),
    (N'FUNCTION'),
    (N'GET'),
    (N'GLOBAL'),
    (N'GO'),
    (N'GOTO'),
    (N'GRANT'),
    (N'GROUP'),
    (N'HANDLER'),
    (N'HAVING'),
    (N'IDENTITY'),
    (N'IMMEDIATE'),
    (N'INDEX'),
    (N'INDEXED'),
    (N'INDICATOR'),
    (N'INITIALLY'),
    (N'INNER'),
    (N'INOUT'),
    (N'INPUT'),
    (N'INSENSITIVE'),
    (N'INSERT'),
    (N'INTERSECT'),
    (N'INTO'),
    (N'ISOLATION'),
    (N'JOIN'),
    (N'KEY'),
    (N'LANGUAGE'),
    (N'LAST'),
    (N'LEAVE'),
    (N'LEVEL'),
    (N'LOCAL'),
    (N'LONGATTRIBUTE'),
    (N'LOOP'),
    (N'MODIFIES'),
    (N'MODULE'),
    (N'NAMES'),
    (N'NATIONAL'),
    (N'NATURAL'),
    (N'NEXT'),
    (N'NULLIF'),
    (N'ON'),
    (N'ONLY'),
    (N'OPEN'),
    (N'OPTION'),
    (N'ORDER'),
    (N'OUT'),
    (N'OUTER'),
    (N'OUTPUT'),
    (N'OVERLAPS'),
    (N'OWNER'),
    (N'PARTIAL'),
    (N'PATH'),
    (N'PRECISION'),
    (N'PREPARE'),
    (N'PRESERVE'),
    (N'PRIMARY'),
    (N'PRIOR'),
    (N'PRIVILEGES'),
    (N'PROCEDURE'),
    (N'PUBLIC'),
    (N'READ'),
    (N'READS'),
    (N'REFERENCES'),
    (N'RELATIVE'),
    (N'REPEAT'),
    (N'RESIGNAL'),
    (N'RESTRICT'),
    (N'RETURN'),
    (N'RETURNS'),
    (N'REVOKE'),
    (N'ROLLBACK'),
    (N'ROUTINE'),
    (N'ROW'),
    (N'ROWS'),
    (N'SCHEMA'),
    (N'SCROLL'),
    (N'SECTION'),
    (N'SELECT'),
    (N'SEQ'),
    (N'SEQUENCE'),
    (N'SESSION'),
    (N'SESSION_USER'),
    (N'SESSION_USERID'),
    (N'SET'),
    (N'SIGNAL'),
    (N'SOME'),
    (N'SPACE'),
    (N'SPECIFIC'),
    (N'SQL'),
    (N'SQLCODE'),
    (N'SQLERROR'),
    (N'SQLEXCEPTION'),
    (N'SQLSTATE'),
    (N'SQLWARNING'),
    (N'STATEMENT'),
    (N'STRINGATTRIBUTE'),
    (N'SUM'),
    (N'SYSACC'),
    (N'SYSHGH'),
    (N'SYSLNK'),
    (N'SYSNIX'),
    (N'SYSTBLDEF'),
    (N'SYSTBLDSC'),
    (N'SYSTBT'),
    (N'SYSTBTATT'),
    (N'SYSTBTDEF'),
    (N'SYSUSR'),
    (N'SYSTEM_USER'),
    (N'SYSVIW'),
    (N'SYSVIWCOL'),
    (N'TABLE'),
    (N'TABLETYPE'),
    (N'TEMPORARY'),
    (N'TRANSACTION'),
    (N'TRANSLATE'),
    (N'TRANSLATION'),
    (N'TRIGGER'),
    (N'UNDO'),
    (N'UNION'),
    (N'UNIQUE'),
    (N'UNTIL'),
    (N'UPDATE'),
    (N'USAGE'),
    (N'USER'),
    (N'USING'),
    (N'VALUE'),
    (N'VALUES'),
    (N'VIEW'),
    (N'WHERE'),
    (N'WHILE'),
    (N'WITH'),
    (N'WORK'),
    (N'WRITE'),
    (N'ALLSCHEMAS'),
    (N'ALLTABLES'),
    (N'ALLVIEWS'),
    (N'ALLVIEWTEXTS'),
    (N'ALLCOLUMNS'),
    (N'ALLINDEXES'),
    (N'ALLINDEXCOLS'),
    (N'ALLUSERS'),
    (N'ALLTBTS'),
    (N'TABLEPRIVILEGES'),
    (N'TBTPRIVILEGES'),
    (N'MYSCHEMAS'),
    (N'MYTABLES'),
    (N'MYTBTS'),
    (N'MYVIEWS'),
    (N'SCHEMAVIEWS'),
    (N'DUAL'),
    (N'SCHEMAPRIVILEGES'),
    (N'SCHEMATABLES'),
    (N'STATISTICS'),
    (N'USRTBL'),
    (N'STRINGTABLE'),
    (N'LONGTABLE'),
    (N'DOUBLETABLE'),
    (N'SELECT * FROM');

UPDATE sw.sensitive_words
SET severity_level = 1,
    updated_at = SYSUTCDATETIME(),
    updated_by = N'system'
WHERE normalized_word IN (
    SELECT LOWER(LTRIM(RTRIM(word)))
    FROM @sql_keywords
);

INSERT INTO sw.sensitive_words (
    word,
    severity_level,
    created_by
)
SELECT
    source.word,
    1,
    N'system'
FROM @sql_keywords source
WHERE NOT EXISTS (
    SELECT 1
    FROM sw.sensitive_words target
    WHERE target.normalized_word = LOWER(LTRIM(RTRIM(source.word)))
);

DELETE target
FROM sw.sensitive_words target
WHERE target.normalized_word IN (N'testbadword', N'restricted phrase', N'scam')
  AND target.created_by = N'seed'
  AND NOT EXISTS (
      SELECT 1
      FROM sw.sensitive_word_audit_log audit
      WHERE audit.sensitive_word_id = target.sensitive_word_id
  );

SET NOCOUNT OFF;
GO
